In [ ]:
import pandas as pd
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
import numpy as np

# Load Dataset

In [ ]:
df=pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vQdgDWC_WW5tLOUpIjGwNNsponV0gcRWaea1hs1WN1HyCvO26Wp43h7AXwVqk7AVa4QMFULEX0yTD8F/pub?output=csv")

In [ ]:
df

DSE    Sem1    Sem2    Sem3    Sem4    Sem5  Sem6  Sem7        CLASS
0     NO  ATKT 1    7.92     8.2    8.18    8.48  8.85  9.73  DISTINCTION
1     NO    7.24    7.12  ATKT 2    6.98  ATKT 2  6.72  7.73           FC
2     NO  ATKT 3  ATKT 1    6.44    6.18      YD  FAIL  FAIL           YD
3     NO  ATKT 2  ATKT 1       6    6.02      YD  FAIL  FAIL           YD
4     NO  ATKT 3  ATKT 1  ATKT 6  ATKT 7      YD  FAIL  FAIL           YD
..   ...     ...     ...     ...     ...     ...   ...   ...          ...
206  YES     NaN     NaN  ATKT 1    8.12    9.61  9.65  9.91  DISTINCTION
207  YES     NaN     NaN     7.8    8.86    9.87  9.91  9.95  DISTINCTION
208  YES     NaN     NaN  ATKT 1    8.76      10    10    10  DISTINCTION
209  YES     NaN     NaN    8.02    9.02    9.91  9.96    10  DISTINCTION
210  YES     NaN     NaN    6.56    8.28    9.74  9.87    10  DISTINCTION

[211 rows x 9 columns]

In [ ]:
df["CLASS"].unique()

array(['DISTINCTION', 'FC', 'YD'], dtype=object)

# Replace Duplicates

In [ ]:
df["Sem1"].unique()

array(['ATKT 1', '7.24', 'ATKT 3', 'ATKT 2', 'ATKT 4', 'ATKT 5', 'ATKT4',
       'ATKT1', 'ATKT 6', '8.44', '7.72', '8.2', '8.8', '7.2', nan,
       '8.56', '7.4', '8.64', '7.28', '9.84', '8.12', '8.52', '9.08',
       '7.96', '7.56', '7.44', '8.68', '9.48', '6.88', '7.84', '9.12',
       '7.92', '7.76', '7.04', '6.56', '8.28', '8.32', '8.76', '8.72',
       '7.88', '7.48', '7.52', '8.36'], dtype=object)

In [ ]:
df['Sem1']=df["Sem1"].replace('ATKT1',"ATKT 1")
df['Sem1']=df["Sem1"].replace('ATKT4',"ATKT 4")

In [ ]:
df["Sem1"].unique()

array(['ATKT 1', '7.24', 'ATKT 3', 'ATKT 2', 'ATKT 4', 'ATKT 5', 'ATKT 6',
       '8.44', '7.72', '8.2', '8.8', '7.2', nan, '8.56', '7.4', '8.64',
       '7.28', '9.84', '8.12', '8.52', '9.08', '7.96', '7.56', '7.44',
       '8.68', '9.48', '6.88', '7.84', '9.12', '7.92', '7.76', '7.04',
       '6.56', '8.28', '8.32', '8.76', '8.72', '7.88', '7.48', '7.52',
       '8.36'], dtype=object)

In [ ]:
df["Sem2"].unique()

array(['7.92', '7.12', 'ATKT 1', 'FAIL', '7.16', '7.36', '7.42', '8.6',
       '7.78', '7.52', '8.04', '8.84', '8.48', '6.82', '6.98', '7.04',
       '7.5', nan, '8.38', 'ATKT 5', '8.94', '8.34', 'ATKT 3', 'ATKT 4',
       '9.42', '7.74', '8.58', '8.74', 'ATKT 2', 'ATKT 6', '8.18', '7.62',
       '7.38', '9.28', '6.9', '8.82', '7.34', 'ATKT', '7.24', '7.48',
       '6.52', '8.42', '8.1', '7.28', '7.82', '8.5', '8.22', '8.2',
       '8.54', '8.72', '7.4', '6.96', '7.14', '8.06'], dtype=object)

In [ ]:
df['Sem2']=df["Sem2"].replace('ATKT',"ATKT 1")

In [ ]:
df["Sem2"].unique()

array(['7.92', '7.12', 'ATKT 1', 'FAIL', '7.16', '7.36', '7.42', '8.6',
       '7.78', '7.52', '8.04', '8.84', '8.48', '6.82', '6.98', '7.04',
       '7.5', nan, '8.38', 'ATKT 5', '8.94', '8.34', 'ATKT 3', 'ATKT 4',
       '9.42', '7.74', '8.58', '8.74', 'ATKT 2', 'ATKT 6', '8.18', '7.62',
       '7.38', '9.28', '6.9', '8.82', '7.34', '7.24', '7.48', '6.52',
       '8.42', '8.1', '7.28', '7.82', '8.5', '8.22', '8.2', '8.54',
       '8.72', '7.4', '6.96', '7.14', '8.06'], dtype=object)

In [ ]:
df["Sem3"].unique()

array(['8.2', 'ATKT 2', '6.44', '6', 'ATKT 6', 'FAIL', '7.04', 'ATKT 4',
       '7.24', '7.56', 'ATKT 1', '7.32', '6.8', 'ATKT 5', 'ATKT 3', '7.6',
       '7.84', '6.36', '7.72', '7.8', '6.32', '6.72', 'ATKT 7', '6.12',
       '7.76', '7.4', '7.28', '7.88', '8.4', '8.88', '8.44', '6.84',
       '6.6', '7.52', '9.2', '8.24', '6.96', '6.28', '8.08', '7.44',
       '8.04', '9.36', '8.56', '8.68', '7.16', '6.76', '7.48', '8.02',
       '8.36', '7.36', '6.52', '8.48', '7.02', '6.92', '6.56'],
      dtype=object)

In [ ]:
df["Sem4"].unique()

array(['8.18', '6.98', '6.18', '6.02', 'ATKT 7', 'FAIL', '7.18', '6.78',
       '7.48', 'ATKT 3', 'ATKT 1', 'ATKT 5', '7.32', 'ATKT 4', '6.16',
       '8.22', '6.4', '7.04', '7.86', '7.34', '6.64', 'ATKT 2', '7.58',
       '8.26', '8.52', '6.94', '6.28', '7.7', '6.6', '6.48', '7.12',
       '7.5', '7.92', '7.96', '6.54', '7.08', '8.1', '8.44', '6.82',
       '8.68', '8.36', '8.04', '7.2', '7.6', '6.76', '6.36', '7.16',
       '6.68', '7.52', '7.84', '7.46', '8.84', '8.06', '8.12', '6.24',
       '7.74', '8.86', '9.68', '8.16', '8.56', '9.28', '8.28', '8.34',
       '9.18', '8.08', '8.02', '8.32', '8.38', '8.94', '8.74', '8.78',
       '8', '9.01', '7.94', '8.88', '8.62', '8.07', '8.72', '8.42',
       '7.78', '9.04', '8.54', '8.92', '8.09', '8.76', '9.02'],
      dtype=object)

In [ ]:
df["Sem5"].unique()

array(['8.48', 'ATKT 2', 'YD', 'FAIL', '7.43', '6.22', '6.74', '8.57',
       'ATKT 1', '6.91', '8.74', '7.52', '8.7', '7.61', '7.26', '8.17',
       '6.78', '7.39', 'ATKT1', '6.61', '6.96', '7.17', '7.83', '7.87',
       '7.7', '7.78', '7', '7.74', '8.78', '8.64', '7.65', '8.3', '6.43',
       '8', '7.35', '8.52', '8.87', '7.48', '5.96', '6.39', '8.04',
       'ATKT 3', '8.61', '7.57', '5.7', '8.22', '9.04', '7.91', '8.35',
       '8.13', '8.43', '9.96', '10', '9.74', '9.57', '9.52', '9.87',
       '9.61', '9.65', '9.7', '9.91', '9.78', '9.3'], dtype=object)

In [ ]:
df['Sem5']=df["Sem5"].replace('ATKT1',"ATKT 1")

In [ ]:
df["Sem6"].unique()

array(['8.85', '6.72', 'FAIL', '7.09', '6.76', '7.46', 'ATKT 2', '8.48',
       '6.63', '7.07', '7.48', '8.74', '7.96', '8.7', '7.87', '7.02',
       '7.22', '7.33', '8.33', 'ATKT 1', '7.15', '7.43', '6.74', '6.96',
       '7.35', '7.91', '7.26', '6.89', '8.02', '6.8', '7.04', '7.78',
       '8.3', '8.11', '7.24', '7.8', '8.78', '9.17', '8.46', '8.83',
       '8.04', '8.41', '8.52', '9.07', '7.72', '9.35', '8.39', '7.2',
       '7.65', '7.28', '7.61', '7.37', '8.15', '7.59', '8.35', '8.96',
       '8.37', '7.89', '9.04', '8.43', '8.61', '9.3', '8.5', '9.37',
       '8.65', '8.8', '9', '8.13', '9.98', '9.89', '10', '9.87', '9.67',
       '9.63', '9.85', '9.78', '9.8', '9.72', '9.93', '9.83', '9.57',
       '9.76', '9.96', '9.91', '9.59', '9.48', '9.65'], dtype=object)

In [ ]:
df["Sem7"].unique()

array(['9.73', '7.73', 'FAIL', '8.32', 'ATKT 1', '7.59', '7.91', '7.82',
       '9.27', '8.64', '9.41', '8.82', '8.41', '8.95', '6.91', '8.55',
       '8.36', '9', '8.77', '8.86', '8.05', '8.27', '8.18', '8.91',
       '9.09', '9.82', '10', '9.64', '9.95', '9.86', '9.55', '9.45',
       '9.36', '9.68', '9.23', '9.5', '9.14', '9.91', '9.77', '9.59',
       '9.32'], dtype=object)

In [ ]:
df

DSE    Sem1    Sem2    Sem3    Sem4    Sem5  Sem6  Sem7        CLASS
0     NO  ATKT 1    7.92     8.2    8.18    8.48  8.85  9.73  DISTINCTION
1     NO    7.24    7.12  ATKT 2    6.98  ATKT 2  6.72  7.73           FC
2     NO  ATKT 3  ATKT 1    6.44    6.18      YD  FAIL  FAIL           YD
3     NO  ATKT 2  ATKT 1       6    6.02      YD  FAIL  FAIL           YD
4     NO  ATKT 3  ATKT 1  ATKT 6  ATKT 7      YD  FAIL  FAIL           YD
..   ...     ...     ...     ...     ...     ...   ...   ...          ...
206  YES     NaN     NaN  ATKT 1    8.12    9.61  9.65  9.91  DISTINCTION
207  YES     NaN     NaN     7.8    8.86    9.87  9.91  9.95  DISTINCTION
208  YES     NaN     NaN  ATKT 1    8.76      10    10    10  DISTINCTION
209  YES     NaN     NaN    8.02    9.02    9.91  9.96    10  DISTINCTION
210  YES     NaN     NaN    6.56    8.28    9.74  9.87    10  DISTINCTION

[211 rows x 9 columns]

# Transform and create column for ATKT, YD and FAIL 

In [ ]:
def is_atkt(value):
    if 'ATKT' in str(value):
        return True
    else:
        return False

In [ ]:
def atkt_count(value):
    if 'ATKT' in str(value):
        res=value.split()
        return res[-1]
    else:
        return 0

In [ ]:
def is_yd(value):
    if 'YD' in str(value):
        return True
    else:
        return False

In [ ]:
def is_fail(value):
    if 'FAIL' in str(value):
        return True
    else:
        return False

In [ ]:
df["Sem 1 ATKT"]=df["Sem1"].apply(is_atkt)
df["Sem 1 ATKT Count"]=df["Sem1"].apply(atkt_count)
df["Sem 1 YD"]=df["Sem1"].apply(is_yd)
df["Sem 1 Fail"]=df["Sem1"].apply(is_fail)

In [ ]:
df["Sem 2 ATKT"]=df["Sem2"].apply(is_atkt)
df["Sem 2 ATKT Count"]=df["Sem2"].apply(atkt_count)
df["Sem 2 YD"]=df["Sem2"].apply(is_yd)
df["Sem 2 Fail"]=df["Sem2"].apply(is_fail)

In [ ]:
df["Sem 3 ATKT"]=df["Sem3"].apply(is_atkt)
df["Sem 3 ATKT Count"]=df["Sem3"].apply(atkt_count)
df["Sem 3 YD"]=df["Sem3"].apply(is_yd)
df["Sem 3 Fail"]=df["Sem3"].apply(is_fail)

In [ ]:
df["Sem 4 ATKT"]=df["Sem4"].apply(is_atkt)
df["Sem 4 ATKT Count"]=df["Sem4"].apply(atkt_count)
df["Sem 4 YD"]=df["Sem4"].apply(is_yd)
df["Sem 4 Fail"]=df["Sem4"].apply(is_fail)

In [ ]:
df["Sem 5 ATKT"]=df["Sem5"].apply(is_atkt)
df["Sem 5 ATKT Count"]=df["Sem5"].apply(atkt_count)
df["Sem 5 YD"]=df["Sem5"].apply(is_yd)
df["Sem 5 Fail"]=df["Sem5"].apply(is_fail)

In [ ]:
df["Sem 6 ATKT"]=df["Sem6"].apply(is_atkt)
df["Sem 6 ATKT Count"]=df["Sem6"].apply(atkt_count)
df["Sem 6 YD"]=df["Sem6"].apply(is_yd)
df["Sem 6 Fail"]=df["Sem6"].apply(is_fail)

In [ ]:
df["Sem 7 ATKT"]=df["Sem7"].apply(is_atkt)
df["Sem 7 ATKT Count"]=df["Sem7"].apply(atkt_count)
df["Sem 7 YD"]=df["Sem7"].apply(is_yd)
df["Sem 7 Fail"]=df["Sem7"].apply(is_fail)

In [ ]:
df.head()

DSE    Sem1    Sem2    Sem3    Sem4    Sem5  Sem6  Sem7        CLASS  \
0  NO  ATKT 1    7.92     8.2    8.18    8.48  8.85  9.73  DISTINCTION   
1  NO    7.24    7.12  ATKT 2    6.98  ATKT 2  6.72  7.73           FC   
2  NO  ATKT 3  ATKT 1    6.44    6.18      YD  FAIL  FAIL           YD   
3  NO  ATKT 2  ATKT 1       6    6.02      YD  FAIL  FAIL           YD   
4  NO  ATKT 3  ATKT 1  ATKT 6  ATKT 7      YD  FAIL  FAIL           YD   

   Sem 1 ATKT  ... Sem 5 YD  Sem 5 Fail  Sem 6 ATKT  Sem 6 ATKT Count  \
0        True  ...    False       False       False                 0   
1       False  ...    False       False       False                 0   
2        True  ...     True       False       False                 0   
3        True  ...     True       False       False                 0   
4        True  ...     True       False       False                 0   

  Sem 6 YD  Sem 6 Fail  Sem 7 ATKT  Sem 7 ATKT Count Sem 7 YD  Sem 7 Fail  
0    False       False       False                 0    False       False  
1    False       False       False                 0    False       False  
2    False        True       False                 0    False        True  
3    False        True       False                 0    False        True  
4    False        True       False                 0    False        True  

[5 rows x 37 columns]

# Replace ATKT, YD and FAIL with minimal Value

In [ ]:
def replace_atkt(value):
    if 'ATKT' in str(value):
        return 5
    else:
        return value

In [ ]:
def replace_yd(value):
    if 'YD' in str(value):
        return 4
    else:
        return value

In [ ]:
def replace_fail(value):
    if 'FAIL' in str(value):
        return 3
    else:
        return value

In [ ]:
df["Sem1"]=df["Sem1"].apply(replace_atkt)
df["Sem1"]=df["Sem1"].apply(replace_yd)
df["Sem1"]=df["Sem1"].apply(replace_fail)
df["Sem1"]=df["Sem1"].astype(float)
df["Sem 1 ATKT Count"]=df["Sem 1 ATKT Count"].astype(float)

In [ ]:
df["Sem2"]=df["Sem2"].apply(replace_atkt)
df["Sem2"]=df["Sem2"].apply(replace_yd)
df["Sem2"]=df["Sem2"].apply(replace_fail)
df["Sem2"]=df["Sem2"].astype(float)
df["Sem 2 ATKT Count"]=df["Sem 2 ATKT Count"].astype(float)

In [ ]:
df["Sem3"]=df["Sem3"].apply(replace_atkt)
df["Sem3"]=df["Sem3"].apply(replace_yd)
df["Sem3"]=df["Sem3"].apply(replace_fail)
df["Sem3"]=df["Sem3"].astype(float)
df["Sem 3 ATKT Count"]=df["Sem 3 ATKT Count"].astype(float)

In [ ]:
df["Sem4"]=df["Sem4"].apply(replace_atkt)
df["Sem4"]=df["Sem4"].apply(replace_yd)
df["Sem4"]=df["Sem4"].apply(replace_fail)
df["Sem4"]=df["Sem4"].astype(float)
df["Sem 4 ATKT Count"]=df["Sem 4 ATKT Count"].astype(float)

In [ ]:
df["Sem5"]=df["Sem5"].apply(replace_atkt)
df["Sem5"]=df["Sem5"].apply(replace_yd)
df["Sem5"]=df["Sem5"].apply(replace_fail)
df["Sem5"]=df["Sem5"].astype(float)
df["Sem 5 ATKT Count"]=df["Sem 5 ATKT Count"].astype(float)

In [ ]:
df["Sem6"]=df["Sem6"].apply(replace_atkt)
df["Sem6"]=df["Sem6"].apply(replace_yd)
df["Sem6"]=df["Sem6"].apply(replace_fail)
df["Sem6"]=df["Sem6"].astype(float)
df["Sem 6 ATKT Count"]=df["Sem 6 ATKT Count"].astype(float)

In [ ]:
df["Sem7"]=df["Sem7"].apply(replace_atkt)
df["Sem7"]=df["Sem7"].apply(replace_yd)
df["Sem7"]=df["Sem7"].apply(replace_fail)
df["Sem7"]=df["Sem7"].astype(float)
df["Sem 7 ATKT Count"]=df["Sem 7 ATKT Count"].astype(float)

In [ ]:
df.head()

DSE  Sem1  Sem2  Sem3  Sem4  Sem5  Sem6  Sem7        CLASS  Sem 1 ATKT  ...  \
0  NO  5.00  7.92  8.20  8.18  8.48  8.85  9.73  DISTINCTION        True  ...   
1  NO  7.24  7.12  5.00  6.98  5.00  6.72  7.73           FC       False  ...   
2  NO  5.00  5.00  6.44  6.18  4.00  3.00  3.00           YD        True  ...   
3  NO  5.00  5.00  6.00  6.02  4.00  3.00  3.00           YD        True  ...   
4  NO  5.00  5.00  5.00  5.00  4.00  3.00  3.00           YD        True  ...   

   Sem 5 YD  Sem 5 Fail  Sem 6 ATKT  Sem 6 ATKT Count  Sem 6 YD  Sem 6 Fail  \
0     False       False       False               0.0     False       False   
1     False       False       False               0.0     False       False   
2      True       False       False               0.0     False        True   
3      True       False       False               0.0     False        True   
4      True       False       False               0.0     False        True   

   Sem 7 ATKT  Sem 7 ATKT Count  Sem 7 YD  Sem 7 Fail  
0       False               0.0     False       False  
1       False               0.0     False       False  
2       False               0.0     False        True  
3       False               0.0     False        True  
4       False               0.0     False        True  

[5 rows x 37 columns]

# **Create another dataframe for DSE Students**

In [ ]:
dse=df[df.isnull().any(axis=1)]

In [ ]:
dse

DSE  Sem1  Sem2  Sem3  Sem4   Sem5   Sem6   Sem7        CLASS  \
54   YES   NaN   NaN  6.80  7.32   6.96   7.35   9.00  DISTINCTION   
55   YES   NaN   NaN  6.80  5.00   5.00   7.91   9.00  DISTINCTION   
56   YES   NaN   NaN  5.00  6.60   7.17   7.26   8.36           FC   
57   YES   NaN   NaN  5.00  5.00   5.00   6.89   8.77           FC   
58   YES   NaN   NaN  5.00  5.00   7.83   8.02   8.86           FC   
59   YES   NaN   NaN  5.00  5.00   7.87   7.33   8.05           FC   
60   YES   NaN   NaN  6.00  5.00   5.00   5.00   8.27           FC   
61   YES   NaN   NaN  6.12  6.48   5.00   6.80   8.18           FC   
62   YES   NaN   NaN  7.76  7.12   6.78   7.04   8.86  DISTINCTION   
63   YES   NaN   NaN  7.76  7.50   7.70   7.78   8.86  DISTINCTION   
64   YES   NaN   NaN  7.40  7.18   7.78   8.30   9.27  DISTINCTION   
65   YES   NaN   NaN  5.00  7.92   5.00   8.11   8.77  DISTINCTION   
66   YES   NaN   NaN  7.24  7.12   5.00   8.02   5.00  DISTINCTION   
67   YES   NaN   NaN  5.00  5.00   7.00   7.24   8.86  DISTINCTION   
68   YES   NaN   NaN  7.76  7.96   7.74   7.96   9.00  DISTINCTION   
69   YES   NaN   NaN  5.00  6.54   7.26   7.80   8.91  DISTINCTION   
70   YES   NaN   NaN  7.28  7.08   8.78   8.78   9.09  DISTINCTION   
124  YES   NaN   NaN  7.40  7.32   8.22   9.04   9.64  DISTINCTION   
125  YES   NaN   NaN  5.00  5.00   7.78   8.43  10.00  DISTINCTION   
126  YES   NaN   NaN  7.52  7.52   7.78   8.61   9.55  DISTINCTION   
127  YES   NaN   NaN  7.72  7.84   7.78   9.30   9.86  DISTINCTION   
128  YES   NaN   NaN  5.00  5.00   5.00   8.04   9.86  DISTINCTION   
129  YES   NaN   NaN  7.72  7.46   5.00   8.50   9.23  DISTINCTION   
130  YES   NaN   NaN  9.20  8.84   9.04   9.37  10.00  DISTINCTION   
131  YES   NaN   NaN  5.00  8.06   7.91   8.65  10.00  DISTINCTION   
132  YES   NaN   NaN  5.00  5.00   5.00   7.28   9.36           FC   
133  YES   NaN   NaN  8.24  8.12   8.35   8.96   9.95  DISTINCTION   
134  YES   NaN   NaN  5.00  5.00   5.00   7.89   9.86  DISTINCTION   
135  YES   NaN   NaN  6.96  7.16   8.13   8.46   9.50  DISTINCTION   
136  YES   NaN   NaN  6.28  6.24   8.17   8.80   9.14  DISTINCTION   
137  YES   NaN   NaN  8.08  7.74   8.00   8.70  10.00  DISTINCTION   
138  YES   NaN   NaN  5.00  5.00   7.00   8.04  10.00  DISTINCTION   
139  YES   NaN   NaN  7.52  6.98   8.43   9.00   9.86  DISTINCTION   
140  YES   NaN   NaN  7.44  7.46   8.35   9.04   9.55  DISTINCTION   
141  YES   NaN   NaN  6.36  5.00   7.70   8.13  10.00  DISTINCTION   
203  YES   NaN   NaN  7.76  8.78   9.91   9.91  10.00  DISTINCTION   
204  YES   NaN   NaN  5.00  8.09  10.00  10.00  10.00  DISTINCTION   
205  YES   NaN   NaN  5.00  9.18   9.91   9.93  10.00  DISTINCTION   
206  YES   NaN   NaN  5.00  8.12   9.61   9.65   9.91  DISTINCTION   
207  YES   NaN   NaN  7.80  8.86   9.87   9.91   9.95  DISTINCTION   
208  YES   NaN   NaN  5.00  8.76  10.00  10.00  10.00  DISTINCTION   
209  YES   NaN   NaN  8.02  9.02   9.91   9.96  10.00  DISTINCTION   
210  YES   NaN   NaN  6.56  8.28   9.74   9.87  10.00  DISTINCTION   

     Sem 1 ATKT  ...  Sem 5 YD  Sem 5 Fail  Sem 6 ATKT  Sem 6 ATKT Count  \
54        False  ...     False       False       False               0.0   
55        False  ...     False       False       False               0.0   
56        False  ...     False       False       False               0.0   
57        False  ...     False       False       False               0.0   
58        False  ...     False       False       False               0.0   
59        False  ...     False       False       False               0.0   
60        False  ...     False       False        True               2.0   
61        False  ...     False       False       False               0.0   
62        False  ...     False       False       False               0.0   
63        False  ...     False       False       False               0.0   
64        False  ...     False       False       False               0.0   
65        Fa

# *Drop Null values from main dataframe*

In [ ]:
df.dropna(inplace=True)

In [ ]:
df

DSE  Sem1  Sem2  Sem3  Sem4  Sem5  Sem6   Sem7        CLASS  Sem 1 ATKT  \
0    NO  5.00  7.92  8.20  8.18  8.48  8.85   9.73  DISTINCTION        True   
1    NO  7.24  7.12  5.00  6.98  5.00  6.72   7.73           FC       False   
2    NO  5.00  5.00  6.44  6.18  4.00  3.00   3.00           YD        True   
3    NO  5.00  5.00  6.00  6.02  4.00  3.00   3.00           YD        True   
4    NO  5.00  5.00  5.00  5.00  4.00  3.00   3.00           YD        True   
..   ..   ...   ...   ...   ...   ...   ...    ...          ...         ...   
198  NO  5.00  8.06  7.72  8.78  9.91  9.93  10.00  DISTINCTION        True   
199  NO  5.00  7.40  7.32  8.52  9.74  9.59   9.59  DISTINCTION        True   
200  NO  5.00  5.00  5.00  8.42  9.30  9.48   9.32  DISTINCTION        True   
201  NO  5.00  3.00  3.00  3.00  3.00  3.00   3.00           YD        True   
202  NO  5.00  5.00  5.00  8.92  9.87  9.93  10.00  DISTINCTION        True   

     ...  Sem 5 YD  Sem 5 Fail  Sem 6 ATKT  Sem 6 ATKT Count  Sem 6 YD  \
0    ...     False       False       False               0.0     False   
1    ...     False       False       False               0.0     False   
2    ...      True       False       False               0.0     False   
3    ...      True       False       False               0.0     False   
4    ...      True       False       False               0.0     False   
..   ...       ...         ...         ...               ...       ...   
198  ...     False       False       False               0.0     False   
199  ...     False       False       False               0.0     False   
200  ...     False       False       False               0.0     False   
201  ...     False        True       False               0.0     False   
202  ...     False       False       False               0.0     False   

     Sem 6 Fail  Sem 7 ATKT  Sem 7 ATKT Count  Sem 7 YD  Sem 7 Fail  
0         False       False               0.0     False       False  
1         False       False               0.0     False       False  
2          True       False               0.0     False        True  
3          True       False               0.0     False        True  
4          True       False               0.0     False        True  
..          ...         ...               ...       ...         ...  
198       False       False               0.0     False       False  
199       False       False               0.0     False       False  
200       False       False               0.0     False       False  
201        True       False               0.0     False        True  
202       False       False               0.0     False       False  

[168 rows x 37 columns]

# **Calculate mean value of DSE students of 4 semesters.**

In [ ]:
dse["Sem1"]=dse.loc[:, ["Sem3","Sem4","Sem5","Sem6","Sem7"]].mean(axis=1)
dse["Sem2"]=dse.loc[:, ["Sem3","Sem4","Sem5","Sem6","Sem7"]].mean(axis=1)

<ipython-input-45-b3bb53acea9c>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dse["Sem1"]=dse.loc[:, ["Sem3","Sem4","Sem5","Sem6","Sem7"]].mean(axis=1)
<ipython-input-45-b3bb53acea9c>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dse["Sem2"]=dse.loc[:, ["Sem3","Sem4","Sem5","Sem6","Sem7"]].mean(axis=1)


In [ ]:
dse

DSE   Sem1   Sem2  Sem3  Sem4   Sem5   Sem6   Sem7        CLASS  \
54   YES  7.486  7.486  6.80  7.32   6.96   7.35   9.00  DISTINCTION   
55   YES  6.742  6.742  6.80  5.00   5.00   7.91   9.00  DISTINCTION   
56   YES  6.878  6.878  5.00  6.60   7.17   7.26   8.36           FC   
57   YES  6.132  6.132  5.00  5.00   5.00   6.89   8.77           FC   
58   YES  6.942  6.942  5.00  5.00   7.83   8.02   8.86           FC   
59   YES  6.650  6.650  5.00  5.00   7.87   7.33   8.05           FC   
60   YES  5.854  5.854  6.00  5.00   5.00   5.00   8.27           FC   
61   YES  6.516  6.516  6.12  6.48   5.00   6.80   8.18           FC   
62   YES  7.512  7.512  7.76  7.12   6.78   7.04   8.86  DISTINCTION   
63   YES  7.920  7.920  7.76  7.50   7.70   7.78   8.86  DISTINCTION   
64   YES  7.986  7.986  7.40  7.18   7.78   8.30   9.27  DISTINCTION   
65   YES  6.960  6.960  5.00  7.92   5.00   8.11   8.77  DISTINCTION   
66   YES  6.476  6.476  7.24  7.12   5.00   8.02   5.00  DISTINCTION   
67   YES  6.620  6.620  5.00  5.00   7.00   7.24   8.86  DISTINCTION   
68   YES  8.084  8.084  7.76  7.96   7.74   7.96   9.00  DISTINCTION   
69   YES  7.102  7.102  5.00  6.54   7.26   7.80   8.91  DISTINCTION   
70   YES  8.202  8.202  7.28  7.08   8.78   8.78   9.09  DISTINCTION   
124  YES  8.324  8.324  7.40  7.32   8.22   9.04   9.64  DISTINCTION   
125  YES  7.242  7.242  5.00  5.00   7.78   8.43  10.00  DISTINCTION   
126  YES  8.196  8.196  7.52  7.52   7.78   8.61   9.55  DISTINCTION   
127  YES  8.500  8.500  7.72  7.84   7.78   9.30   9.86  DISTINCTION   
128  YES  6.580  6.580  5.00  5.00   5.00   8.04   9.86  DISTINCTION   
129  YES  7.582  7.582  7.72  7.46   5.00   8.50   9.23  DISTINCTION   
130  YES  9.290  9.290  9.20  8.84   9.04   9.37  10.00  DISTINCTION   
131  YES  7.924  7.924  5.00  8.06   7.91   8.65  10.00  DISTINCTION   
132  YES  6.328  6.328  5.00  5.00   5.00   7.28   9.36           FC   
133  YES  8.724  8.724  8.24  8.12   8.35   8.96   9.95  DISTINCTION   
134  YES  6.550  6.550  5.00  5.00   5.00   7.89   9.86  DISTINCTION   
135  YES  8.042  8.042  6.96  7.16   8.13   8.46   9.50  DISTINCTION   
136  YES  7.726  7.726  6.28  6.24   8.17   8.80   9.14  DISTINCTION   
137  YES  8.504  8.504  8.08  7.74   8.00   8.70  10.00  DISTINCTION   
138  YES  7.008  7.008  5.00  5.00   7.00   8.04  10.00  DISTINCTION   
139  YES  8.358  8.358  7.52  6.98   8.43   9.00   9.86  DISTINCTION   
140  YES  8.368  8.368  7.44  7.46   8.35   9.04   9.55  DISTINCTION   
141  YES  7.438  7.438  6.36  5.00   7.70   8.13  10.00  DISTINCTION   
203  YES  9.272  9.272  7.76  8.78   9.91   9.91  10.00  DISTINCTION   
204  YES  8.618  8.618  5.00  8.09  10.00  10.00  10.00  DISTINCTION   
205  YES  8.804  8.804  5.00  9.18   9.91   9.93  10.00  DISTINCTION   
206  YES  8.458  8.458  5.00  8.12   9.61   9.65   9.91  DISTINCTION   
207  YES  9.278  9.278  7.80  8.86   9.87   9.91   9.95  DISTINCTION   
208  YES  8.752  8.752  5.00  8.76  10.00  10.00  10.00  DISTINCTION   
209  YES  9.382  9.382  8.02  9.02   9.91   9.96  10.00  DISTINCTION   
210  YES  8.890  8.890  6.56  8.28   9.74   9.87  10.00  DISTINCTION   

     Sem 1 ATKT  ...  Sem 5 YD  Sem 5 Fail  Sem 6 ATKT  Sem 6 ATKT Count  \
54        False  ...     False       False       False               0.0   
55        False  ...     False       False       False               0.0   
56        False  ...     False       False       False               0.0   
57        False  ...     False       False       False               0.0   
58        False  ...     False       False       False               0.0   
59        False  ...     False       False       False               0.0   
60        False  ...     False       False        True               2.0   
61        False  ...     False       False       False               0.0   
62        False  ...     False       False       False               0.0   
63        False  ...     False       False       False               0.0   


# Concatenate DSE with main dataframe

In [ ]:
df=df.append(dse)

<ipython-input-47-811ecdabd56c>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df=df.append(dse)


# Check mean value of DSE of sem1 and sem2 for future replacement

In [ ]:
dse["Sem1"].mean()

7.725581395348837

In [ ]:
dse["Sem2"].mean()

7.725581395348837

In [ ]:
class_col=df.pop("CLASS")

In [ ]:
df.insert(36,"CLASS",class_col)

In [ ]:
df

DSE   Sem1   Sem2  Sem3  Sem4   Sem5   Sem6   Sem7  Sem 1 ATKT  \
0     NO  5.000  7.920  8.20  8.18   8.48   8.85   9.73        True   
1     NO  7.240  7.120  5.00  6.98   5.00   6.72   7.73       False   
2     NO  5.000  5.000  6.44  6.18   4.00   3.00   3.00        True   
3     NO  5.000  5.000  6.00  6.02   4.00   3.00   3.00        True   
4     NO  5.000  5.000  5.00  5.00   4.00   3.00   3.00        True   
..   ...    ...    ...   ...   ...    ...    ...    ...         ...   
206  YES  8.458  8.458  5.00  8.12   9.61   9.65   9.91       False   
207  YES  9.278  9.278  7.80  8.86   9.87   9.91   9.95       False   
208  YES  8.752  8.752  5.00  8.76  10.00  10.00  10.00       False   
209  YES  9.382  9.382  8.02  9.02   9.91   9.96  10.00       False   
210  YES  8.890  8.890  6.56  8.28   9.74   9.87  10.00       False   

     Sem 1 ATKT Count  ...  Sem 5 Fail  Sem 6 ATKT  Sem 6 ATKT Count  \
0                 1.0  ...       False       False               0.0   
1                 0.0  ...       False       False               0.0   
2                 3.0  ...       False       False               0.0   
3                 2.0  ...       False       False               0.0   
4                 3.0  ...       False       False               0.0   
..                ...  ...         ...         ...               ...   
206               0.0  ...       False       False               0.0   
207               0.0  ...       False       False               0.0   
208               0.0  ...       False       False               0.0   
209               0.0  ...       False       False               0.0   
210               0.0  ...       False       False               0.0   

     Sem 6 YD  Sem 6 Fail  Sem 7 ATKT  Sem 7 ATKT Count  Sem 7 YD  Sem 7 Fail  \
0       False       False       False               0.0     False       False   
1       False       False       False               0.0     False       False   
2       False        True       False               0.0     False        True   
3       False        True       False               0.0     False        True   
4       False        True       False               0.0     False        True   
..        ...         ...         ...               ...       ...         ...   
206     False       False       False               0.0     False       False   
207     False       False       False               0.0     False       False   
208     False       False       False               0.0     False       False   
209     False       False       False               0.0     False       False   
210     False       False       False               0.0     False       False   

           CLASS  
0    DISTINCTION  
1             FC  
2             YD  
3             YD  
4             YD  
..           ...  
206  DISTINCTION  
207  DISTINCTION  
208  DISTINCTION  
209  DISTINCTION  
210  DISTINCTION  

[211 rows x 37 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 211 entries, 0 to 210
Data columns (total 37 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   DSE               211 non-null    object 
 1   Sem1              211 non-null    float64
 2   Sem2              211 non-null    float64
 3   Sem3              211 non-null    float64
 4   Sem4              211 non-null    float64
 5   Sem5              211 non-null    float64
 6   Sem6              211 non-null    float64
 7   Sem7              211 non-null    float64
 8   Sem 1 ATKT        211 non-null    bool   
 9   Sem 1 ATKT Count  211 non-null    float64
 10  Sem 1 YD          211 non-null    bool   
 11  Sem 1 Fail        211 non-null    bool   
 12  Sem 2 ATKT        211 non-null    bool   
 13  Sem 2 ATKT Count  211 non-null    float64
 14  Sem 2 YD          211 non-null    bool   
 15  Sem 2 Fail        211 non-null    bool   
 16  Sem 3 ATKT        211 non-null    bool   
 1

In [ ]:
label_encoder = LabelEncoder()

In [ ]:
df["DSE"]=label_encoder.fit_transform(df['DSE'])

In [ ]:
df["DSE"].unique()

array([0, 1])

In [ ]:
df["Sem 1 ATKT"]=label_encoder.fit_transform(df['Sem 1 ATKT'])
df["Sem 1 YD"]=label_encoder.fit_transform(df['Sem 1 YD'])
df["Sem 1 Fail"]=label_encoder.fit_transform(df['Sem 1 Fail'])

In [ ]:
df["Sem 2 ATKT"]=label_encoder.fit_transform(df['Sem 2 ATKT'])
df["Sem 2 YD"]=label_encoder.fit_transform(df['Sem 2 YD'])
df["Sem 2 Fail"]=label_encoder.fit_transform(df['Sem 2 Fail'])

In [ ]:
df["Sem 3 ATKT"]=label_encoder.fit_transform(df['Sem 3 ATKT'])
df["Sem 3 YD"]=label_encoder.fit_transform(df['Sem 3 YD'])
df["Sem 3 Fail"]=label_encoder.fit_transform(df['Sem 3 Fail'])

In [ ]:
df["Sem 4 ATKT"]=label_encoder.fit_transform(df['Sem 4 ATKT'])
df["Sem 4 YD"]=label_encoder.fit_transform(df['Sem 4 YD'])
df["Sem 4 Fail"]=label_encoder.fit_transform(df['Sem 4 Fail'])

In [ ]:
df["Sem 5 ATKT"]=label_encoder.fit_transform(df['Sem 5 ATKT'])
df["Sem 5 YD"]=label_encoder.fit_transform(df['Sem 5 YD'])
df["Sem 5 Fail"]=label_encoder.fit_transform(df['Sem 5 Fail'])

In [ ]:
df["Sem 6 ATKT"]=label_encoder.fit_transform(df['Sem 6 ATKT'])
df["Sem 6 YD"]=label_encoder.fit_transform(df['Sem 6 YD'])
df["Sem 6 Fail"]=label_encoder.fit_transform(df['Sem 6 Fail'])

In [ ]:
df["Sem 7 ATKT"]=label_encoder.fit_transform(df['Sem 7 ATKT'])
df["Sem 7 YD"]=label_encoder.fit_transform(df['Sem 7 YD'])
df["Sem 7 Fail"]=label_encoder.fit_transform(df['Sem 7 Fail'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 211 entries, 0 to 210
Data columns (total 37 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   DSE               211 non-null    int64  
 1   Sem1              211 non-null    float64
 2   Sem2              211 non-null    float64
 3   Sem3              211 non-null    float64
 4   Sem4              211 non-null    float64
 5   Sem5              211 non-null    float64
 6   Sem6              211 non-null    float64
 7   Sem7              211 non-null    float64
 8   Sem 1 ATKT        211 non-null    int64  
 9   Sem 1 ATKT Count  211 non-null    float64
 10  Sem 1 YD          211 non-null    int64  
 11  Sem 1 Fail        211 non-null    int64  
 12  Sem 2 ATKT        211 non-null    int64  
 13  Sem 2 ATKT Count  211 non-null    float64
 14  Sem 2 YD          211 non-null    int64  
 15  Sem 2 Fail        211 non-null    int64  
 16  Sem 3 ATKT        211 non-null    int64  
 1

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[: ,:-1],df["CLASS"],test_size=0.2,random_state=101)

In [ ]:
logReg=LogisticRegression()

In [ ]:
logReg.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
pred=logReg.predict(x_test)

In [ ]:
accuracy_score(y_test,pred)

0.9069767441860465

In [ ]:
confusion_matrix(y_test,pred)

array([[28,  2,  0],
       [ 2,  3,  0],
       [ 0,  0,  8]])

In [ ]:
Naive_Bayes = GaussianNB()
Naive_Bayes.fit(x_train, y_train)

GaussianNB()

In [ ]:
pred=Naive_Bayes.predict(x_test)

In [ ]:
accuracy_score(y_test,pred)

0.8837209302325582

In [ ]:
confusion_matrix(y_test,pred)

array([[28,  2,  0],
       [ 3,  2,  0],
       [ 0,  0,  8]])

In [ ]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
pred=knn.predict(x_test)

In [ ]:
accuracy_score(y_test,pred)

0.8837209302325582

In [ ]:
confusion_matrix(y_test,pred)

array([[27,  3,  0],
       [ 2,  3,  0],
       [ 0,  0,  8]])

In [ ]:
svm_clf = svm.SVC()

In [ ]:
svm_clf.fit(x_train, y_train)
pred = svm_clf.predict(x_test)

In [ ]:
accuracy_score(y_test,pred)

0.9534883720930233

In [ ]:
confusion_matrix(y_test,pred)

array([[29,  1,  0],
       [ 1,  4,  0],
       [ 0,  0,  8]])

In [ ]:
dtc = DecisionTreeClassifier()

In [ ]:
dtc.fit(x_train, y_train)
pred = dtc.predict(x_test)

In [ ]:
accuracy_score(y_test,pred)

0.9534883720930233

In [ ]:
confusion_matrix(y_test,pred)

array([[30,  0,  0],
       [ 2,  3,  0],
       [ 0,  0,  8]])

In [ ]:
randForest=RandomForestClassifier()

In [ ]:
randForest.fit(x_train,y_train)

RandomForestClassifier()

In [ ]:
pred=randForest.predict(x_test)

In [ ]:
accuracy_score(y_test,pred)

0.9534883720930233

In [ ]:
confusion_matrix(y_test,pred)

array([[30,  0,  0],
       [ 2,  3,  0],
       [ 0,  0,  8]])

In [ ]:
svm_clf = svm.SVC()

In [ ]:
svm_clf.fit(df.iloc[:,:-1], df["CLASS"])
pred = svm_clf.predict(x_test)

In [ ]:
accuracy_score(y_test,pred)

0.9534883720930233

In [ ]:
confusion_matrix(y_test,pred)

array([[29,  1,  0],
       [ 1,  4,  0],
       [ 0,  0,  8]])

In [ ]:
import pickle

In [ ]:
pickle.dump(svm_clf, open('model.pkl', 'wb'))